export const expression = [
    { expression: "What a mess", translation: "Que bagunça" },
    { expression: "Piece of cake", translation: "Moleza" },
    { expression: "A dime a dozen", translation: "Dez por uma dúzia" },
    { expression: "Break a leg", translation: "Boa sorte" },
    { expression: "Bite the bullet", translation: "Enfrentar uma situação difícil com coragem" },
    { expression: "Let the cat out of the bag", translation: "Revelar um segredo" },
    { expression: "On the ball", translation: "Atento e alerta" },
    { expression: "Run away", translation: "Fugir" },
    { expression: "Spill the beans", translation: "Revelar informações confidenciais" },
    { expression: "The ball is in your court", translation: "A bola está com você" },
    { expression: "All ears", translation: "Atento, ouvindo com atenção" },
    { expression: "Barking up the wrong tree", translation: "Procurando no lugar errado" },
    { expression: "Better late than never", translation: "Antes tarde do que nunca" },
    { expression: "Break the ice", translation: "Quebrar o gelo" },
    { expression: "Costs an arm and a leg", translation: "Muito caro" },
    { expression: "Drive someone up the wall", translation: "Enlouquecer alguém" },
    { expression: "Fit as a fiddle", translation: "Muito saudável" },
    { expression: "Hold your horses", translation: "Acalme-se, espere um momento" },
    { expression: "In a nutshell", translation: "Resumidamente" },
    { expression: "Kill two birds with one stone", translation: "Matar dois coelhos com uma cajadada só" },
    { expression: "Leave no stone unturned", translation: "Não deixar pedra sobre pedra" },
    { expression: "Miss the boat", translation: "Perder uma oportunidade" },
    { expression: "No pain, no gain", translation: "Sem esforço, sem recompensa" },
    { expression: "Off the hook", translation: "Livrar-se de uma situação difícil" },
    { expression: "Piece of pie", translation: "Moleza" },
    { expression: "Put all your eggs in one basket", translation: "Colocar todos os ovos em uma cesta" },
    { expression: "Raining cats and dogs", translation: "Chovendo canivetes" },
    { expression: "The best of both worlds", translation: "O melhor dos dois mundos" },
    { expression: "Under the weather", translation: "Indisposto" },
    { expression: "You can't judge a book by its cover", translation: "Não se pode julgar um livro pela capa" },
    { expression: "Actions speak louder than words", translation: "As ações falam mais alto que as palavras" },
    { expression: "All in the same boat", translation: "Todos na mesma situação" },
    { expression: "Blessing in disguise", translation: "Benção disfarçada" },
    { expression: "Call it a day", translation: "Encerrar o trabalho por hoje" },
    { expression: "Don't cry over spilled milk", translation: "Não chorar pelo leite derramado" },
    { expression: "Every cloud has a silver lining", translation: "Não há mal que não traga algum bem" },
    { expression: "Get a taste of your own medicine", translation: "Provar do próprio veneno" },
    { expression: "Hit the nail on the head", translation: "Acertar em cheio" },
    { expression: "In the blink of an eye", translation: "Num piscar de olhos" },
    { expression: "Keep your fingers crossed", translation: "Torcer os dedos, desejar sorte" },
    { expression: "Like two peas in a pod", translation: "Como duas ervilhas em uma vagem" },
    { expression: "Make a long story short", translation: "Resumindo" },
    { expression: "No use crying over spilled milk", translation: "Não adianta chorar pelo leite derramado" },
    { expression: "On the same page", translation: "Na mesma página" },
    { expression: "Piece of candy", translation: "Moleza" },
    { expression: "Put the cart before the horse", translation: "Inverter a ordem das coisas" },
    { expression: "Raining buckets", translation: "Chovendo baldes" },
    { expression: "The last straw", translation: "A última gota" },
    { expression: "Up in the air", translation: "Indefinido" },
    { expression: "You can't have your cake and eat it too", translation: "Não se pode ter tudo na vida" },
    { expression: "All that glitters is not gold", translation: "Nem tudo que reluz é ouro" },
    { expression: "Barking up the wrong tree", translation: "Procurando no lugar errado" },
    { expression: "Birds of a feather flock together", translation: "Os semelhantes se atraem" },
    { expression: "By the skin of your teeth", translation: "Por um triz" },
    { expression: "Cut to the chase", translation: "Ir direto ao ponto" },
    { expression: "Don't put all your eggs in one basket", translation: "Não coloque todos os ovos em uma cesta" },
    { expression: "Every dog has its day", translation: "A sorte chega para todos" },
    { expression: "Go the extra mile", translation: "Esforçar-se além do necessário" },
    { expression: "Hit the jackpot", translation: "Acertar a loteria" },
    { expression: "Keep your chin up", translation: "Mantenha a cabeça erguida" },
    { expression: "Make hay while the sun shines", translation: "Aproveite enquanto é tempo" },
    { expression: "No stone unturned", translation: "Não deixar pedra sobre pedra" },
    { expression: "One man's trash is another man's treasure", translation: "O lixo de um é o tesouro de outro" },
    { expression: "Out of the frying pan and into the fire", translation: "De mal a pior" },
    { expression: "Playing with fire", translation: "Brincar com fogo" },
    { expression: "Saved by the bell", translation: "Salvo pelo gongo" },
    { expression: "The early bird catches the worm", translation: "Deus ajuda quem cedo madruga" },
    { expression: "Two heads are better than one", translation: "Duas cabeças pensam melhor do que uma" },
    { expression: "You can't make an omelette without breaking eggs", translation: "Não se faz uma omelete sem quebrar ovos" },
    { expression: "All bark and no bite", translation: "Muito barulho e pouca ação" },
    { expression: "Better safe than sorry", translation: "Melhor prevenir do que remediar" },
    { expression: "Cry over spilled milk", translation: "Chorar pelo leite derramado" },
    { expression: "Don't count your chickens before they hatch", translation: "Não conte com o ovo no fiofó da galinha" },
    { expression: "Every cloud has a silver lining", translation: "Não há mal que não traga algum bem" },
    { expression: "Get cold feet", translation: "Ficar com medo ou hesitar antes de fazer algo" },
    { expression: "Hit the jackpot", translation: "Acertar a loteria" },
    { expression: "In hot water", translation: "Envolvido em problemas" },
    { expression: "Jump on the bandwagon", translation: "Seguir a moda, aderir à tendência" },
    { expression: "Make a mountain out of a molehill", translation: "Fazer tempestade em copo d'água" },
    { expression: "No pain, no gain", translation: "Sem esforço, sem recompensa" },
    { expression: "Over the moon", translation: "Extremamente feliz" },
    { expression: "Put all your eggs in one basket", translation: "Colocar todos os ovos na mesma cesta" },
    { expression: "Rain or shine", translation: "Faça sol ou faça chuva" },
    { expression: "The early bird catches the worm", translation: "Deus ajuda quem cedo madruga" },
    { expression: "Two peas in a pod", translation: "Gêmeos idênticos" },
    { expression: "You're pulling my leg", translation: "Você está brincando comigo" },
    { expression: "All in the same boat", translation: "Todos na mesma situação" },
    { expression: "Better late than never", translation: "Antes tarde do que nunca" },
    { expression: "Curiosity killed the cat", translation: "A curiosidade matou o gato" },
    { expression: "Every dog has its day", translation: "A sorte chega para todos" },
    { expression: "Go with the flow", translation: "Aceitar as coisas como elas vêm" },
    { expression: "Hold your horses", translation: "Acalme-se, espere um momento" },
    { expression: "Keep your fingers crossed", translation: "Torcer os dedos, desejar sorte" },
    { expression: "Like two peas in a pod", translation: "Como duas ervilhas em uma vagem" },
    { expression: "Make a long story short", translation: "Resumindo" },
    { expression: "No use crying over spilled milk", translation: "Não adianta chorar pelo leite derramado" },
    { expression: "On the same page", translation: "Na mesma página" },
    { expression: "Rain cats and dogs", translation: "Chover canivetes" },
    { expression: "The last straw", translation: "A gota d'água" },
    { expression: "Up in the air", translation: "Indefinido" },
    { expression: "You can't have your cake and eat it too", translation: "Não se pode ter tudo na vida" },
    { expression: "All that glitters is not gold", translation: "Nem tudo que reluz é ouro" },
    { expression: "Barking up the wrong tree", translation: "Procurando no lugar errado" },
    { expression: "Birds of a feather flock together", translation: "Os semelhantes se atraem" },
    { expression: "By the skin of your teeth", translation: "Por um triz" },
    { expression: "Cut to the chase", translation: "Ir direto ao ponto" },
    { expression: "Don't put all your eggs in one basket", translation: "Não coloque todos os ovos em uma cesta" },
    { expression: "Every dog has its day", translation: "A sorte chega para todos" },
    { expression: "Go the extra mile", translation: "Esforçar-se além do necessário" },
    { expression: "Hit the jackpot", translation: "Acertar a loteria" },
    { expression: "Keep your chin up", translation: "Mantenha a cabeça erguida" },
    { expression: "Make hay while the sun shines", translation: "Aproveite enquanto é tempo" },
    { expression: "No stone unturned", translation: "Não deixar pedra sobre pedra" },
    { expression: "One man's trash is another man's treasure", translation: "O lixo de um é o tesouro de outro" },
    { expression: "Out of the frying pan and into the fire", translation: "De mal a pior" },
    { expression: "Playing with fire", translation: "Brincando com fogo" },
    { expression: "Saved by the bell", translation: "Salvo pelo gongo" },
    { expression: "The early bird catches the worm", translation: "Deus ajuda quem cedo madruga" },
    { expression: "Two heads are better than one", translation: "Duas cabeças pensam melhor do que uma" },
    { expression: "You can't make an omelette without breaking eggs", translation: "Não se faz uma omelete sem quebrar ovos" },
    { expression: "All bark and no bite", translation: "Muito barulho e pouca ação" },
    { expression: "Better safe than sorry", translation: "Mais vale prevenir do que remediar" },
    { expression: "Cry over spilled milk", translation: "Chorar pelo leite derramado" },
    { expression: "Don't count your chickens before they hatch", translation: "Não conte com o ovo no fiofó da galinha" },
    { expression: "Every cloud has a silver lining", translation: "Não há mal que não traga algum bem" },
    { expression: "Get cold feet", translation: "Ficar com medo ou hesitar antes de fazer algo" },
    { expression: "Hit the jackpot", translation: "Acertar a loteria" },
    { expression: "A picture is worth a thousand words", translation: "Uma imagem vale mais que mil palavras" },
    { expression: "In hot water", translation: "Envolvido em problemas" },
    { expression: "Jump on the bandwagon", translation: "Seguir a moda, aderir à tendência" },
    { expression: "Make a mountain out of a molehill", translation: "Fazer tempestade em copo d'água" },
    { expression: "No pain, no gain", translation: "Sem esforço, sem recompensa" },
    { expression: "Over the moon", translation: "Extremamente feliz" },
    { expression: "Put all your eggs in one basket", translation: "Colocar todos os ovos na mesma cesta" },
    { expression: "Rain or shine", translation: "Faça sol ou faça chuva" },
    { expression: "The early bird catches the worm", translation: "Deus ajuda quem cedo madruga" },
    { expression: "Two peas in a pod", translation: "Gêmeos idênticos" },
    { expression: "You're pulling my leg", translation: "Você está brincando comigo" },
    { expression: "All in the same boat", translation: "Todos na mesma situação" },
    { expression: "Actions speak louder than words", translation: "As ações falam mais alto que as palavras" },
    { expression: "Beauty is in the eye of the beholder", translation: "A beleza está nos olhos de quem vê" },
    { expression: "Don't judge a book by its cover", translation: "Não julgue um livro pela capa" },
    { expression: "Every cloud has a silver lining", translation: "Nem tudo é ruim, há algo de bom em cada situação" }
]