export const wordsPt = [
    { word: "outcomes", translation: "resultados" },
    { word: "entails", translation: "implica" },
    { word: "measure", translation: "medir" },
    { word: "summary", translation: "resumo" },
    { word: "everage", translation: "media" },
    { word: "achievement", translation: "conquista" },
    { word: "standard", translation: "padrão" },
    { word: "expectancy", translation: "expectativa" },
    { word: "entering", translation: "entrando" },
    { word: "gross", translation: "bruta(o)" },
    { word: "income", translation: "renda" },
    { word: "end up", translation: "terminar" },
    { word: "inequality", translation: "desigualdade" },
    { word: "broader", translation: "mais amplo" },
    { word: "", translation: "" },
    { word: "fuller", translation: "mais completo" },
    { word: "annex", translation: "anexo" },
    { word: "poverty", translation: "pobreza" },
    { word: "reasoning", translation: "raciocínio" },
    { word: "healthcare", translation: "assistência médica" },
    { word: "diseases", translation: "doenças" },
    { word: "childrenhood", translation: "childrenhood" },
    { word: "proxy", translation: "procurador" },
    { word: "Knowledgeable", translation: "bem informado" },
    { word: "effective", translation: "eficaz" },
    { word: "both", translation: "tanto/ambos" },
    { word: "adoption", translation: "adoção" },
    { word: "Inspirational", translation: "inspiradora" },
    { word: "leadership", translation: "liderança" },
    { word: "overcome", translation: "superar" },
    { word: "ambitious", translation: "ambiciosa" },
    { word: "avoid", translation: "evitar" },
    { word: " misunderstandings", translation: "mal entendido" },
    { word: "continuous", translation: "continua(o)" },
    { word: "stay", translation: "manter-se/ficar" },
    { word: "updated", translation: "atualizado(a)" },
    { word: "trends", translation: "tendências" },
    { word: "promote", translation: "promover" },
    { word: "encourage", translation: "incentivar/encorajar/fomentar" },
    { word: "set", translation: "estabelecer/setar/por/colocar" },
    { word: "valuables", translation: "valiosos(as)" },
    { word: "lead", translation: "levar" },
    { word: "proactive", translation: "proativa(o)" },
    { word: "issues", translation: "problemas/surgir" },
    { word: "growth", translation: "crescimento" },
    { word: "performance", translation: "desempenho/performance" },
    { word: "align", translation: "alinhar" },
    { word: "common", translation: "comun" },
    { word: "towards", translation: "em direção a" },
    { word: "maintain", translation: "manter" },
    { word: "healthy", translation: "saudável"},
    { word: "well-being", translation: "bem-estar"},
    { word: "provide", translation: "implementar/fornocer"},
    { word: "accountability", translation: "responsabilidade"},
    { word: "commitment", translation: "comprometimento"},
    { word: "unscrew", translation: "desaparafusar" },
    { word: "fit", translation: "ajustar/encaixe" },
    { word: "supposed", translation: "suposto(a)" },
    { word: "cave", translation: "caverna" },
    { word: "scratched", translation: "arranhado(a)/riscada" },
    { word: "swep", translation: "varrer" },
    { word: "meet", translation: "conhecer/encontrar" },
    { word: "quickly", translation: "rapidamente/velocidade" },
    { word: "ensure", translation: "asegurar/garantir" },
    { word: "despite", translation: "apesar de" },
    { word: "effort", translation: "esforço" },
    { word: "discussed", translation: "descutiu(rão)" },
    { word: "late", translation: "tarde" },
    { word: "took", translation: "pegou/levou/fez" },
    { word: "kept", translation: "manteve" },
    { word: "were", translation: "foram" },
    { word: "subject", translation: "assunto" },
    { word: "made", translation: "fez/feito" },
    { word: "sketch", translation: "esboço" },
    { word: "managed", translation: "conseguiu/gerenciou" },
    { word: "goals", translation: "objetivos" },
    { word: "due", translation: "devido/por causa de" },
    { word: "revealed", translation: "revelou/revelado" },
    { word: "evident", translation: "evidente" },
    { word: "previously", translation: "anteriormente" },
    { word: "successfully", translation: "com sucesso" },
    { word: "exceeded", translation: "acima de/da" },
    { word: "significantly", translation: "significativamente" },
    { word: "consumers", translation: "consumidores" },
    { word: "adopt", translation: "adotar" },
    { word: "approach", translation: "estratégias/abordagem" },
    { word: "unexpected", translation: "inesperado" },
    { word: "during", translation: "durante" },
    { word: "adjust", translation: "ajustar" },
    { word: "costumers", translation: "clientes" },
    { word: "swept", translation: "varrida(o)" },
    { word: "bakery", translation: "padaria" },
    { word: "strut", translation: "suporte / escorar" },
    { word: "rug", translation: "tapete" },
    { word: "pleasing", translation: "agradável" },
    { word: "hopping", translation: "saltitar / pular" },
    { word: "terrify", translation: "aterrorizar" },
    { word: "appointments", translation: "compromissos" },
    { word: "although", translation: "embora" },
    { word: "equally", translation: "igualmente" },
    { word: "properly", translation: "corretamente / apropiadamente" },
    { word: "glass", translation: "vidro / copo" },
    { word: "gum", translation: "chiclete" },
    { word: "spare", translation: "poupar / reserva" },
    { word: "door handle", translation: "maçaneta" },
    { word: "roller", translation: "rolo" },
    { word: "attached", translation: "pegado(a) / anexada" },
    { word: "earring", translation: "brinco" },
    { word: "bendy", translation: "flexível" },
    { word: "awards", translation: "prêmios" },
    { word: "drill bit", translation: "broca" },
    { word: "guidance", translation: "orientação" },
    { word: "spicy", translation: "apimentada" },
    { word: "dang", translation: "caramba" },
    { word: "folks", translation: "pessoas" },
    { word: "overland", translation: "por terra" },
    { word: "laundromats", translation: "lavanderia" },
    { word: "either", translation: "escolher entre / qualquer um" },
    { word: "starving", translation: "morrendo de fome" },
    { word: "old-fashioned", translation: "fora de moda" },
    { word: "hash", translation: "corte / picado / cerquilha" },
    { word: "trent", translation: "trêmulo" },
    { word: "appliance", translation: "utensílio/ferramentas" },
    { word: "purchase", translation: "comprar" },
    { word: "full-size", translation: "espaçoso(a)/grande" },
    { word: "pup", translation: "filhote/cachorro" },
    { word: "Cuddle", translation: "abraçar" },
    { word: "Cuddle up", translation: "aconchegue-se" },
    { word: "spread out", translation: "espalhar-se/estender-se" },
    { word: "dank", translation: "úmido/frio" },
    { word: "blow", translation: "soprar/golpe/explosão" },
    { word: "swivel", translation: "giratório(a)" },
    { word: "sweating", translation: "suando" },
    { word: "lifesaver", translation: "salva-vidas" },
    { word: "hotter", translation: "mais quente" },
    { word: "unconditional", translation: "incondicional" },
    { word: "lay", translation: "deitar/leigo" },
    { word: "deal", translation: "acordo/negócio" },
    { word: "screw", translation: "parafuso " },
    { word: "boom", translation: "estrondo" },
    { word: "eqquiped", translation: "equipado" },
    { word: "stealing", translation: "roubando" },
    { word: "release", translation: "liberar" },
    { word: "jumbo", translation: "enorme/grande" },
    { word: "assemble", translation: "montar" },
    { word: "furniture", translation: "movel/mobília" },
    { word: "junk", translation: "porcaria" },
    { word: "rolls", translation: "rolos" },
    { word: "assembly", translation: "conjunto" },
    { word: "poop", translation: "cocô" },
    { word: "exhilarating", translation: "emocionante" },
    { word: "propane", translation: "botijão" },
    { word: "sealed", translation: "celado/fechado" },
    { word: "drill", translation: "furar" },
    { word: "stick", translation: "grudar/vara/pau/bastão" },
    { word: "ultimately", translation: "por fim" },
    { word: "bury", translation: "enterrar" },
    { word: "haule", translation: "transportar" },
    { word: "revenue", translation: "receita" },
    { word: "label", translation: "rótulo" },
    { word: "warm up", translation: "aquecimento" },
    { word: "reveal", translation: "revelar" },
    { word: "heck", translation: "caramba/puxa/diabos" },
    { word: "doll", translation: "boneco(a)" },
    { word: "bounce", translation: "quicar" },
    { word: "make´em", translation: "faça-os" },
    { word: "wear", translation: "vestir" },
    { word: "glow", translation: "brilho" },
    { word: "tide", translation: "maré" },
    { word: "swallow", translation: "engolir" },
    { word: "thunder", translation: "trovão" },
    { word: "whenever", translation: "sempre que" },
    { word: "speech", translation: "discurso" },
    { word: "unbending", translation: "inflexivel/firme" },
    { word: "faith", translation: "fé" },
    { word: "dead", translation: "morto(a)" },
    { word: "ember", translation: "brasa" },
    { word: "ashes", translation: "cinzas" },
    { word: "crumpled", translation: "amassada" },
    { word: "sirens", translation: "sirenes" },
    { word: "get through", translation: "atravessar/superar" },
    { word: "fray", translation: "briga" },
    { word: "unchain", translation: "desencadear" },
    { word: "underneath", translation: "debaixo de" },
    { word: "unsay", translation: "retratar-se" },
    { word: "pennies", translation: "centavos" },
    { word: "begun", translation: "começou" },
    { word: "freak", translation: "doido" },
    { word: "spit", translation: "saliva" },
    { word: "worm", translation: "verme/minhoca" },
    { word: "gone", translation: "se foi/sumiu/desapareceu" },
    { word: "saunder", translation: "sábio(a)" },
    { word: "beg", translation: "implorar" },
    { word: "hairpin", translation: "grampo" },
    { word: "choke", translation: "estrangular/asfixiar" },
    { word: "shiver", translation: "arrepio" },
    { word: "diss", translation: "insulto" },
    { word: "doorman", translation: "porteiro" },
    { word: "chore", translation: "tarefa" },
    { word: "creepy", translation: "repugnante" },
    { word: "encounter", translation: "encontros" },
    { word: "bloom", translation: "florescer/a flor" },
    { word: "awkward", translation: "estranho(a)" },
    { word: "laundry", translation: "lavanderia" },
    { word: "speechless", translation: "sem palavras" },
    { word: "pan", translation: "panela" },
    { word: "wavy", translation: "ondulada" },
    { word: "lip", translation: "lábio" },
    { word: "leak", translation: "vazar" },
    { word: "ripped", translation: "rasgada" },
    { word: "drew", translation: "desenhou" },
    { word: "pebbly", translation: "pedregosa" },
    { word: "riverbank", translation: "a beira do rio" },
    { word: "reshaping", translation: "remodelando" },
    { word: "increasingly", translation: "cada vez mais" },
    { word: "ubiquitous", translation: "onipresente" },
    { word: "strides", translation: "avanços" },
    { word: "overall", translation: "geral" },
    { word: "witnessed", translation: "presenciar" },
    { word: "tailored", translation: "sob medida" },
    { word: "enhance", translation: "melhorar/realçar" },
    { word: "harness", translation: "aproveitar" },
    { word: "tiredness", translation: "cansaço" },
    { word: "blanket", translation: "cobertor" },
    { word: "cricket", translation: "grilo" },
    { word: "guess", translation: "adivinhar" },
    { word: "dear", translation: "querido(a)" },
    { word: "defunding", translation: "desfinanciamento" },
    { word: "filling", translation: "enchimento/enchendo" },
    { word: "missiles", translation: "mísseis" },
    { word: "shipping", translation: "envio" },
    { word: "lungs", translation: "pulmões" },
    { word: "murdered", translation: "assassinada" },
    { word: "pregnant", translation: "grávida" },
    { word: "weak", translation: "fraco(a)" },
    { word: "surrounded", translation: "cercado" },
    { word: "burst", translation: "explodido/explosão" },
    { word: "drowned", translation: "afogado(a)" },
    { word: "owe", translation: "dever" },
    { word: "overdue", translation: "atrasado(a)" },
    { word: "stolen", translation: "roubado(a)" },
    { word: "couples", translation: "casais" },
    { word: "crumble", translation: "desmoronar" },
    { word: "dreamt", translation: "sonhou" },
    { word: "stand", translation: "ficar" },
    { word: "poles", translation: "postes" },
    { word: "clawed", translation: "garras" },
    { word: "chained", translation: "acorrentado(a)" },
    { word: "hit", translation: "bater" },
    { word: "arcade", translation: "videogames" },
    { word: "awake", translation: "acordado(a)" },
    { word: "forgiveness", translation: "perdão" },
    { word: "broke-ass", translation: "falida" },
    { word: "swear", translation: "jurar" },
    { word: "phatness", translation: "farsa" },
    { word: "acknowledge", translation: "reconhecer" },
    { word: "snap", translation: "estalo/foto" },
    { word: "spin", translation: "rodar/girar" },
    { word: "loyalty", translation: "lealdade" },
    { word: "upon", translation: "sobre" },
    { word: "fearless", translation: "destemido(a)" },
    { word: "outweigh", translation: "superar" },
    { word: "dust", translation: "pó" },
    { word: "throne", translation: "trono" },
    { word: "lighthouse", translation: "farol" },
    { word: "miracle", translation: "milagre" },
    { word: "seams", translation: "costura" },
    { word: "seamstress", translation: "costureira" },
    { word: "overnight", translation: "pela noite" },
    { word: "shop", translation: "loja/estabelecimento" },
    { word: "salted", translation: "salgado(a)" },
    { word: "Butter", translation: "manteiga" },
    { word: "churn", translation: "Agitar/Mexer" },
    { word: "noticeably", translation: "notavelmente" },
    { word: "scary", translation: "assustador/assustado" },
    { word: "Collagen", translation: "colágeno" },
    { word: "frothy", translation: "espumosa" },
    { word: "shut", translation: "fechar" },
    { word: "undefeated", translation: "invicto(o)" },
    { word: "balcony", translation: "terraço" },
    { word: "reckless", translation: "inconsequente/irresponsável" },
    { word: "tilted", translation: "inclinado(a)" },
    { word: "dumb", translation: "anestesiado/entorpecido" },
    { word: "faithless", translation: "sem fé/descrente" },
    { word: "pressure", translation: "pressão" },
    { word: "aware", translation: "consciente/ciente" },
    { word: "worshipped", translation: "adorado" },
    { word: "bleak", translation: "desolador/sombrio" },
    { word: "sooner", translation: "mais cedo" },
    { word: "vanished", translation: "desaparecido" },
    { word: "climbing", translation: "escalada" },
    { word: "painting", translation: "pintura" },
    { word: "even", translation: "mesmo/até/ainda" },
    { word: "nightmare", translation: "pesadelo" },
    { word: "take", translation: "levar/pegar/tomar/avaliar" },
    { word: "tear", translation: "rasgar/lágrima/gota" },
    { word: "skin", translation: "pele" },
    { word: "overflowed", translation: "transbordou" },
    { word: "fill", translation: "preencher" },
    { word: "until", translation: "até" },
    { word: "highway", translation: "estrada principal/rodovia" },
    { word: "Self-esteem", translation: "autoestima" },
    { word: "furthest", translation: "mais distante" },
    { word: "proud", translation: "orgulhoso" },
    { word: "trapped", translation: "preso" },
    { word: "messed", translation: "bagunçado/confundido" },
    { word: "snooze", translation: "soneca" },
    { word: "roof", translation: "teto" },
    { word: "smash", translation: "quebrar/esmagar" },
    { word: "nasty", translation: "desagradável / nojento" },
    { word: "forbidden", translation: "proibido / vedado" },
    { word: "naive", translation: "ingênuo / inocente" },
    { word: "sink", translation: "afundar" },
    { word: "dry", translation: "seco" },
    { word: "goddamn", translation: "maldito" },
    { word: "spoon", translation: "colher" },
    { word: "trading", translation: "negociação/comércio" },
    { word: "sunk", translation: "afundou" },
    { word: "bragging", translation: "vaidade" },
    { word: "sidewalks", translation: "calçadas" },
    { word: "mesmerizing", translation: "hipnotizante / fascinante" },
    { word: "rather", translation: "preferencialmente/bastante/em vez disso" },
    { word: "thrill", translation: "emoção / excitação" },
    { word: "illness", translation: "doença" },
    { word: "bloodsucker", translation: "sanguessuga" },
    { word: "strawberry", translation: "morango" },
    { word: "devil", translation: "diabo" },
    { word: "famefucker", translation: "FDP que quer atenção" },
    { word: "hunt", translation: "caçar" },
    { word: "bleeding", translation: "sangramento" },
    { word: "fate", translation: "destino" },
    { word: "selfish", translation: "egoísta" },
    { word: "stare", translation: "encarar" },
    { word: "flares", translation: "sinalizadores" },
    { word: "fallen", translation: "caído" },
    { word: "outfit", translation: "roupa" },
    { word: "bend", translation: "dobrar/curvar" },
    { word: "pour", translation: "despejar" },
    { word: "dishonor", translation: "desonra" },
    { word: "grab", translation: "pegar/agarrar/tomar" },
    { word: "diaper", translation: "fraldas" },
    { word: "washcloths", translation: "toalha de rosto" },
    { word: "bulleproof", translation: "a prova de balas" },
    { word: "blame", translation: "culpar" },
    { word: "blaze", translation: "chama 🔥" },
    { word: "desire", translation: "desejo" },
    { word: "heartache", translation: "sofrimento" },
    { word: "bow", translation: "gravata/arco/reverência/curvar-se" },
    { word: "dazzling", translation: "deslubrante" },
    { word: "lust", translation: "luxuria" },
    { word: "atone", translation: "expiar/reparar" },
    { word: "tied", translation: "atado/amarrado" },
    { word: "pride", translation: "orgulho" },
    { word: "guilt", translation: "culpa" },
    { word: "rise", translation: "elevar/suspender" },
    { word: "warmth", translation: "calor/temperatura agradavel" },
    { word: "sadness", translation: "tristeza/melancolia" },
    { word: "moonlight", translation: "luz da lua" },
    { word: "pale", translation: "palido/esbranquiçado" },
    { word: "snare", translation: "armadilha" },
    { word: "awakened", translation: "despertado/acordado" },
    { word: "swore", translation: "jurar / praguejar" },
    { word: "grace", translation: "graça/perdão" },
    { word: "shemeless", translation: "sem vergonha" },
    { word: "scream", translation: "grito / gritar" },
    { word: "erase", translation: "apagar/eliminar" },
    { word: "rage", translation: "raive / furia" },
    { word: "mess it up", translation: "bagunçar" },
    { word: "dirt", translation: "sujeira / poeira" },
    { word: "regret", translation: "arrependimento / remorso" },
    { word: "blink", translation: "piscar" },
    { word: "afford", translation: "ter condiçoes/recursos para" },
    { word: "concerns", translation: "preocupações" },
    { word: "lukewar", translation: "morna(o)" },
    { word: "burning", translation: "queimando" },
    { word: "damming", translation: "impedir / atrapalhar / obstruir" },
    { word: "nearest", translation: "mais proximo" },
    { word: "forwards", translation: "em frente / para frente" },
    { word: "sparkly", translation: "brilhante" },
    { word: "sheer", translation: "completo / puro " },
    { word: "cup", translation: "xícara / copo" },
    { word: "towel", translation: "toalha" },
    { word: "predictable", translation: "previsível" },
    { word: "dehydrated", translation: "desidratado(a)" },
    { word: "proceed", translation: "continuar / proceder" },
    { word: "disgusting", translation: "repugnante / nojenta" },
    { word: "indoor", translation: "interior / interno" },
    { word: "outdoor", translation: "exterior / externo" },
    { word: "pair", translation: "par / dupla" },
    { word: "nail", translation: "unha" },
    { word: "unsheen", translation: "invisível" },
    { word: "heart-shaped", translation: "em formato de coração" },
    { word: "syrup", translation: "xarope" },
    { word: "mold", translation: "mofo / molde" },
    { word: "layer", translation: "camada" },
    { word: "displacement", translation: "deslocamento" },
    { word: "arise", translation: "surgir" },
    { word: "Overlay", translation: "sobreposição" },
    { word: "fasten", translation: "prender / apertar / fixar" },
    { word: "belts", translation: " cintos" },
    { word: "hike", translation: "caminhada" },
    { word: "plunge", translation: "mergulho" },
    { word: "stretch", translation: "alongar / esticar" },
    { word: "campside", translation: "acampamento" },
    { word: "overrun", translation: "superação" },
    { word: "throwing out", translation: "jogando fora" },
    { word: "campground", translation: "area de acampamento" },
    { word: "stirring", translation: "mexendo" },
    { word: "rotten", translation: "podre" },
    { word: "Furthermore", translation: "além disso" },
    { word: "accurate", translation: "precisa (algo exato)" },
    { word: "misinformation", translation: "desenformação" },
    { word: "Striking", translation: "inpressionante" },
    { word: "drawbacks", translation: "desvantagens" },
    { word: "shine", translation: "brilhar" },
    { word: "ray", translation: "raio" },
    { word: "saw", translation: "vi" },
    { word: "brought", translation: "trouxe" },
    { word: "burden", translation: "fardo" },
    { word: "sinner", translation: "pecador" },
    { word: "intertwine", translation: "entrelaçar" },
    { word: "poison", translation: "toxico/veneno" },
    { word: "poisonous", translation: "venenonoso" },
    { word: "tighter", translation: "apertado" },
    { word: "hints", translation: "dicas" },
    { word: "handwritters", translation: "manuscrito" },
    { word: "penned", translation: "escrito" },
    { word: "lack", translation: "falta/carência/lacuna" },
    { word: "fetch", translation: "buscar" },
    { word: "manufacturing", translation: "fabricação" },
    { word: "cuisine", translation: "culinária" },
    { word: "Sunrise", translation: "nascer do sol" },
    { word: "cozy", translation: "aconchegante" },
    { word: "flavors", translation: "sabores" },
    { word: "cottage", translation: "cabana" },
    { word: "sunset", translation: "por do sol" },
    { word: "shoreline", translation: "litoral" },
    { word: "smell", translation: "cheiro" },
    { word: "beachside", translation: "á beira do mar" },
    { word: "breeze", translation: "brisa" },
    { word: "gentle", translation: "getil / suave" },
    { word: "ham", translation: "presunto" },
    { word: "shore", translation: "costa (da praia)" },
    { word: "recipes", translation: "receitas" },
    { word: "spices", translation: "especiarias" },
    { word: "gear", translation: "engrenagem" },
    { word: "chop", translation: "cortar" },
    { word: "herbs", translation: "ervas" },
    { word: "apron", translation: "avental" },
    { word: "freshest", translation: "mais frescos" },
    { word: "edges", translation: "bordas" },
    { word: "Frankly", translation: "francamente" },
    { word: "whirly", translation: "rodopiante" },
    { word: "Louder", translation: "Mais alto" },
    { word: "seashells", translation: "conchas do mar" },
    { word: "bark", translation: "latir" },
    { word: "sandy", translation: "arenosa" },
    { word: "boil", translation: "ferver" },
    { word: "Hanging", translation: "pendurada(o)" },
    { word: "wounds", translation: "ferimentos" },
    { word: "blood", translation: "sangue" },
    { word: "fade", translation: "desaparecer" },
    { word: "Chasing", translation: "perseguindo" },
    { word: "gazing", translation: "contemplando" },
    { word: "forsake", translation: "abandonar" },
    { word: "seeking", translation: "procurando / buscando" },
    { word: "helpless", translation: "desamparado(a)" },
    { word: "fault", translation: "falta" },
    { word: "inch", translation: "polegada" },
    { word: "hold", translation: "segurar" },
    { word: "sauce", translation: "molho" },
    { word: "healing", translation: "cura" },
    { word: "alive", translation: "viva" },
    { word: "knees", translation: "joelhos" },
    { word: "slip", translation: "escorregar" },
    { word: "salt", translation: "sal" },
    { word: "crossed", translation: "atravessei / crusei" },
    { word: "skeptical", translation: "cético" },
    { word: "lips", translation: "lábios" },
    { word: "cupid", translation: "cupido" },
    { word: "ride", translation: "andar de/ passeio" },
    { word: "mood", translation: "humor" },
    { word: "dizzy", translation: "tonto" },
    { word: "fur", translation: "pelo" },
    { word: "fear", translation: "medo" },
    { word: "meant", translation: "significou" },
    { word: "house", translation: "casa" },
    { word: "bird", translation: "pássaro" },
    { word: "rain", translation: "chuva" },
    { word: "lick", translation: "lamber" },
    { word: "star", translation: "estrela" },
    { word: "arrow", translation: "cetas / flexas" },
    { word: "fool", translation: "bobo / idiota" },
    { word: "city", translation: "cidade" },
    { word: "country", translation: "país" },
    { word: "world", translation: "mundo" },
    { word: "street", translation: "rua" },
    { word: "river", translation: "rio" },
    { word: "flew", translation: "voou" },
    { word: "drag", translation: "arrastar" },
    { word: "beach", translation: "praia" },
    { word: "mountain", translation: "montanha" },
    { word: "forest", translation: "floresta" },
    { word: "lake", translation: "lago" },
    { word: "ocean", translation: "oceano" },
    { word: "garden", translation: "jardim" },
    { word: "park", translation: "parque" },
    { word: "bridge", translation: "ponte" },
    { word: "road", translation: "estrada" },
    { word: "cloud", translation: "nuvem" },
    { word: "else", translation: "outro" },
    { word: "kiss", translation: "beijar" },
    { word: "heartbeat", translation: "batimento cardiaco" },
    { word: "moon", translation: "lua" },
    { word: "sun", translation: "sol" },
    { word: "star", translation: "estrela" },
    { word: "light", translation: "luz" },
    { word: "dark", translation: "escuro" },
    { word: "red", translation: "vermelho" },
    { word: "blue", translation: "azul" },
    { word: "wherever", translation: "onde quer que" },
    { word: "green", translation: "verde" },
    { word: "yellow", translation: "amarelo" },
    { word: "orange", translation: "laranja" },
    { word: "purple", translation: "roxo" },
    { word: "pink", translation: "rosa" },
    { word: "brown", translation: "marrom" },
    { word: "black", translation: "preto" },
    { word: "white", translation: "branco" },
    { word: "gray", translation: "cinza" },
    { word: "drown", translation: "afogar" },
    { word: "color", translation: "cor" },
    { word: "paint", translation: "pintar" },
    { word: "draw", translation: "desenhar" },
    { word: "write", translation: "escrever" },
    { word: "read", translation: "ler" },
    { word: "listen", translation: "ouvir" },
    { word: "speak", translation: "falar" },
    { word: "think", translation: "pensar" },
    { word: "learn", translation: "aprender" },
    { word: "teach", translation: "ensinar" },
    { word: "study", translation: "estudar" },
    { word: "work", translation: "trabalhar" },
    { word: "play", translation: "brincar" },
    { word: "tea", translation: "chá" },
    { word: "dance", translation: "dançar" },
    { word: "sing", translation: "cantar" },
    { word: "swim", translation: "nadar" },
    { word: "run", translation: "correr" },
    { word: "walk", translation: "caminhar" },
    { word: "jump", translation: "pular" },
    { word: "climb", translation: "escalar" },
    { word: "fly", translation: "voar" },
    { word: "drive", translation: "dirigir" },
    { word: "wondering", translation: "perguntando / imaginando" },
    { word: "travel", translation: "viajar" },
    { word: "explore", translation: "explorar" },
    { word: "discover", translation: "descobrir" },
    { word: "create", translation: "criar" },
    { word: "build", translation: "construir" },
    { word: "design", translation: "projetar" },
    { word: "imagine", translation: "imaginar" },
    { word: "dream", translation: "sonhar" },
    { word: "achieve", translation: "alcançar" },
    { word: "succeed", translation: "ter sucesso" },
    { word: "fail", translation: "falhar" },
    { word: "win", translation: "ganhar" },
    { word: "lose", translation: "perder" },
    { word: "help", translation: "ajudar" },
    { word: "support", translation: "apoiar" },
    { word: "encourage", translation: "incentivar" },
    { word: "comfort", translation: "confortar" },
    { word: "believe", translation: "acreditar" },
    { word: "trust", translation: "confiar" },
    { word: "respect", translation: "respeitar" },
    { word: "love", translation: "amar" },
    { word: "hate", translation: "odiar" },
    { word: "forgive", translation: "perdoar" },
    { word: "forget", translation: "esquecer" },
    { word: "remember", translation: "lembrar" },
    { word: "care", translation: "importar-se/cuidado" },
    { word: "share", translation: "compartilhar" },
    { word: "give", translation: "dar" },
    { word: "take", translation: "pegar" },
    { word: "receive", translation: "receber" },
    { word: "buy", translation: "comprar" },
    { word: "sell", translation: "vender" },
    { word: "eat", translation: "comer" },
    { word: "drink", translation: "beber" },
    { word: "cook", translation: "cozinhar" },
    { word: "bake", translation: "assar" },
    { word: "order", translation: "pedir" },
    { word: "pay", translation: "pagar" },
    { word: "save", translation: "economizar" },
    { word: "spend", translation: "gastar" },
    { word: "plan", translation: "planejar" },
    { word: "organize", translation: "organizar" },
    { word: "manage", translation: "gerenciar" },
    { word: "solve", translation: "resolver" },
    { word: "fix", translation: "consertar" },
    { word: "change", translation: "mudar" },
    { word: "adapt", translation: "adaptar" },
    { word: "improve", translation: "melhorar" },
    { word: "grow", translation: "crescer" },
    { word: "develop", translation: "desenvolver" },
    { word: "discover", translation: "descobrir" },
    { word: "explore", translation: "explorar" },
    { word: "learn", translation: "aprender" },
    { word: "understand", translation: "entender" },
    { word: "know", translation: "saber" },
    { word: "think", translation: "pensar" },
    { word: "believe", translation: "acreditar" },
    { word: "doubt", translation: "duvidar" },
    { word: "question", translation: "questionar" },
    { word: "wonder", translation: "maravilhar-se" },
    { word: "explore", translation: "explorar" },
    { word: "create", translation: "criar" },
    { word: "invent", translation: "inventar" },
    { word: "innovate", translation: "inovar" },
    { word: "design", translation: "projetar" },
    { word: "build", translation: "construir" },
    { word: "destroy", translation: "destruir" },
    { word: "break", translation: "quebrar" },
    { word: "repair", translation: "reparar" },
    { word: "fix", translation: "consertar" },
    { word: "change", translation: "mudar" },
    { word: "transform", translation: "transformar" },
    { word: "adapt", translation: "adaptar" },
    { word: "evolve", translation: "evoluir" },
    { word: "grow", translation: "crescer" },
    { word: "develop", translation: "desenvolver" },
    { word: "achieve", translation: "alcançar" },
    { word: "succeed", translation: "ter sucesso" },
    { word: "fail", translation: "falhar" },
    { word: "win", translation: "ganhar" },
    { word: "lose", translation: "perder" },
    { word: "help", translation: "ajudar" },
    { word: "tree", translation: "árvore" },
    { word: "flower", translation: "flor" },
    { word: "book", translation: "livro" },
    { word: "pen", translation: "caneta" },
    { word: "chair", translation: "cadeira" },
    { word: "table", translation: "mesa" },
    { word: "bed", translation: "cama" },
    { word: "window", translation: "janela" },
    { word: "door", translation: "porta" },
    { word: "car", translation: "carro" },
    { word: "bike", translation: "bicicleta" },
    { word: "plane", translation: "avião" },
    { word: "train", translation: "trem" },
    { word: "bus", translation: "ônibus" },
    { word: "boat", translation: "barco" },
    { word: "ship", translation: "navio" },
    { word: "computer", translation: "computador" },
    { word: "phone", translation: "telefone" },
    { word: "music", translation: "música" },
    { word: "movie", translation: "filme" },
    { word: "game", translation: "jogo" },
    { word: "sports", translation: "esportes" },
    { word: "food", translation: "comida" },
    { word: "drink", translation: "bebida" },
    { word: "time", translation: "tempo" },
    { word: "money", translation: "dinheiro" },
    { word: "friend", translation: "amigo" },
    { word: "family", translation: "família" },
    { word: "health", translation: "saúde" },
    { word: "happiness", translation: "felicidade" },
    { word: "musician", translation: "músico" },
    { word: "artist", translation: "artista" },
    { word: "teacher", translation: "professor" },
    { word: "student", translation: "aluno" },
    { word: "doctor", translation: "médico" },
    { word: "engineer", translation: "engenheiro" },
    { word: "scientist", translation: "cientista" },
    { word: "writer", translation: "escritor" },
    { word: "actor", translation: "ator" },
    { word: "actress", translation: "atriz" },
    { word: "singer", translation: "cantor" },
    { word: "dancer", translation: "dançarino" },
    { word: "painter", translation: "pintor" },
    { word: "photographer", translation: "fotógrafo" },
    { word: "chef", translation: "chef" },
    { word: "architect", translation: "arquiteto" },
    { word: "pilot", translation: "piloto" },
    { word: "lawyer", translation: "advogado" },
    { word: "judge", translation: "juiz" },
    { word: "police", translation: "polícia" },
    { word: "firefighter", translation: "bombeiro" },
    { word: "soldier", translation: "soldado" },
    { word: "athlete", translation: "atleta" },
    { word: "gymnast", translation: "ginasta" },
    { word: "pianist", translation: "pianista" },
    { word: "violinist", translation: "violinista" },
    { word: "sculptor", translation: "escultor" },
    { word: "director", translation: "diretor" },
    { word: "manager", translation: "gerente" },
    { word: "leader", translation: "líder" },
    { word: "employee", translation: "funcionário" },
    { word: "customer", translation: "cliente" },
    { word: "volunteer", translation: "voluntário" },
    { word: "citizen", translation: "cidadão" },
    { word: "baby", translation: "bebê" },
    { word: "child", translation: "criança" },
    { word: "teenager", translation: "adolescente" },
    { word: "adult", translation: "adulto" },
    { word: "elder", translation: "idoso" },
    { word: "cow", translation: "vaca" },
    { word: "sheep", translation: "ovelha" },
    { word: "giraffe", translation: "girafa" },
    { word: "hippo", translation: "hipopótamo" },
    { word: "kangaroo", translation: "canguru" },
    { word: "snake", translation: "cobra" },
    { word: "turtle", translation: "tartaruga" },
    { word: "butterfly", translation: "borboleta" },
    { word: "bee", translation: "abelha" },
    { word: "ant", translation: "formiga" },
    { word: "ladybug", translation: "joaninha" },
]