export const acronimos = [
    { acronimo: "WFH", mean: "work from home", translation: "trabalhar de casa" },
    { acronimo: "NGL", mean: "Not gonna lie", translation: "não vou mentir" },
    { acronimo: "FAQ", mean: "Frequently asked question", translation: "pergunta frequentemente feita" },
    { acronimo: "IDC", mean: "i don't care", translation: "eu não me importo" },
    { acronimo: "IG", mean: "I guess", translation: "eu acho" },
    { acronimo: "FYI", mean: "For your information", translation: "para sua informação" },
    { acronimo: "TY", mean: "Thank you", translation: "obrigado" },
    { acronimo: "ASAP", mean: "As soon as possible", translation: "o mais rápido possível" },
    { acronimo: "FR", mean: "For real", translation: "para valer" },
    { acronimo: "IDK", mean: "I don't know", translation: "eu não sei" },
    { acronimo: "BRB", mean: "Be Right Back", translation: "volto logo" },
    { acronimo: "BTW", mean: "By the way", translation: "a propósito" },
    { acronimo: "TBH", mean: "To be honest", translation: "para ser honesto" },
    { acronimo: "LOL", mean: "Laugh out loud", translation: "rir em voz alta" },
    { acronimo: "OMG", mean: "Oh my God", translation: "oh meu Deus" },
    { acronimo: "ROFL", mean: "Rolling on the floor laughing", translation: "rolando no chão de tanto rir" },
    { acronimo: "IMHO", mean: "In my humble opinion", translation: "na minha humilde opinião" },
    { acronimo: "SMH", mean: "Shaking my head", translation: "balançando minha cabeça" },
    { acronimo: "TMI", mean: "Too much information", translation: "informação demais" },
    { acronimo: "YOLO", mean: "You only live once", translation: "você só vive uma vez" },
    { acronimo: "BFF", mean: "Best friends forever", translation: "melhores amigos para sempre" },
    { acronimo: "OMW", mean: "On my way", translation: "a caminho" },
    { acronimo: "FOMO", mean: "Fear of missing out", translation: "medo de perder algo" },
    { acronimo: "JK", mean: "Just kidding", translation: "brincadeira" },
    { acronimo: "ICYMI", mean: "In case you missed it", translation: "caso você tenha perdido" },
    { acronimo: "TIL", mean: "Today I learned", translation: "hoje eu aprendi" },
    { acronimo: "DIY", mean: "Do it yourself", translation: "faça você mesmo" },
    { acronimo: "IRL", mean: "In real life", translation: "na vida real" },
    { acronimo: "AMA", mean: "Ask me anything", translation: "me pergunte qualquer coisa" },
    { acronimo: "GG", mean: "Good game", translation: "bom jogo" }
];
