export const acronimosEs = [
    { acronimo: "WFH", mean: "work from home", translation: "trabajar desde casa" },
    { acronimo: "NGL", mean: "Not gonna lie", translation: "no voy a mentir" },
    { acronimo: "FAQ", mean: "Frequently asked question", translation: "pregunta frecuentemente hecha" },
    { acronimo: "IDC", mean: "i don't care", translation: "no me importa" },
    { acronimo: "IG", mean: "I guess", translation: "supongo" },
    { acronimo: "FYI", mean: "For your information", translation: "para tu información" },
    { acronimo: "TY", mean: "Thank you", translation: "gracias" },
    { acronimo: "ASAP", mean: "As soon as possible", translation: "tan pronto como sea posible" },
    { acronimo: "FR", mean: "For real", translation: "de verdad" },
    { acronimo: "IDK", mean: "I don't know", translation: "no lo sé" },
    { acronimo: "BRB", mean: "Be Right Back", translation: "vuelvo enseguida" },
    { acronimo: "BTW", mean: "By the way", translation: "por cierto" },
    { acronimo: "TBH", mean: "To be honest", translation: "para ser honesto" },
    { acronimo: "LOL", mean: "Laugh out loud", translation: "reírse en voz alta" },
    { acronimo: "OMG", mean: "Oh my God", translation: "oh Dios mío" },
    { acronimo: "ROFL", mean: "Rolling on the floor laughing", translation: "rodando en el suelo de tanto reír" },
    { acronimo: "IMHO", mean: "In my humble opinion", translation: "en mi humilde opinión" },
    { acronimo: "SMH", mean: "Shaking my head", translation: "sacudiendo la cabeza" },
    { acronimo: "TMI", mean: "Too much information", translation: "demasiada información" },
    { acronimo: "YOLO", mean: "You only live once", translation: "solo vives una vez" },
    { acronimo: "BFF", mean: "Best friends forever", translation: "mejores amigos para siempre" },
    { acronimo: "OMW", mean: "On my way", translation: "en camino" },
    { acronimo: "FOMO", mean: "Fear of missing out", translation: "miedo a perderse algo" },
    { acronimo: "JK", mean: "Just kidding", translation: "solo bromeo" },
    { acronimo: "ICYMI", mean: "In case you missed it", translation: "en caso de que te lo hayas perdido" },
    { acronimo: "TIL", mean: "Today I learned", translation: "hoy aprendí" },
    { acronimo: "DIY", mean: "Do it yourself", translation: "hazlo tú mismo" },
    { acronimo: "IRL", mean: "In real life", translation: "en la vida real" },
    { acronimo: "AMA", mean: "Ask me anything", translation: "pregúntame cualquier cosa" },
    { acronimo: "GG", mean: "Good game", translation: "buen juego" }
];
