export const expressionEs = [
    { expression: "Shake a leg", translation: "Apúrate" },
    { expression: "God Bless you", translation: "Dios te bendiga" },
    { expression: "Not at all", translation: "Para nada" },
    { expression: "Let's hit it", translation: "Vamos a por ello" },
    { expression: "I'm on it", translation: "Estoy en ello" },
    { expression: "Give me a break", translation: "Dame un respiro" },
    { expression: "You left me hanging", translation: "Me dejaste en la estacada" },
    { expression: "Say Hello to", translation: "Saluda a" },
    { expression: "Turn yourself around", translation: "Da la vuelta" },
    { expression: "I can handle it", translation: "Puedo con esto" },
    { expression: "What a pity", translation: "Qué lástima" },
    { expression: "I hear you", translation: "Te escucho" },
    { expression: "God willing", translation: "Si Dios quiere" },
    { expression: "Off the hook/chain", translation: "Fuera de serie" },
    { expression: "Bummer", translation: "Qué fastidio" },
    { expression: "Like the back of my Hand", translation: "Como la palma de mi mano" },
    { expression: "Take it easy", translation: "Tómalo con calma" },
    { expression: "Give me a hand", translation: "Échame una mano" },
    { expression: "It Rings a beel", translation: "Me suena" },
    { expression: "You nailed it", translation: "Lo clavaste" },
    { expression: "Get away", translation: "Lárgate" },
    { expression: "Take your time", translation: "Tómate tu tiempo" },
    { expression: "Can you Hold on a second", translation: "¿Puedes esperar un segundo?" },
    { expression: "What a mess", translation: "Qué desastre" },
    { expression: "Do you think so", translation: "¿Tú crees?" },
    { expression: "she stood me up", translation: "Me plantó" },
    { expression: "Piece of cake", translation: "Pan comido" },
    { expression: "A dime a dozen", translation: "A diez centavos la docena" },
    { expression: "Break a leg", translation: "Buena suerte" },
    { expression: "Bite the bullet", translation: "Afrontar una situación difícil con valentía" },
    { expression: "Let the cat out of the bag", translation: "Contar un secreto" },
    { expression: "On the ball", translation: "Estar en la jugada" },
    { expression: "Run away", translation: "Huir" },
    { expression: "Spill the beans", translation: "Revelar un secreto" },
    { expression: "The ball is in your court", translation: "La pelota está en tu tejado" },
    { expression: "All ears", translation: "Todo oídos" },
    { expression: "Barking up the wrong tree", translation: "Buscar en el lugar equivocado" },
    { expression: "Better late than never", translation: "Más vale tarde que nunca" },
    { expression: "Break the ice", translation: "Romper el hielo" },
    { expression: "Costs an arm and a leg", translation: "Cuesta un ojo de la cara" },
    { expression: "Drive someone up the wall", translation: "Volver loco a alguien" },
    { expression: "Fit as a fiddle", translation: "En plena forma" },
    { expression: "Hold your horses", translation: "Cálmate" },
    { expression: "In a nutshell", translation: "En pocas palabras" },
    { expression: "Kill two birds with one stone", translation: "Matar dos pájaros de un tiro" },
    { expression: "Leave no stone unturned", translation: "No dejar piedra sin remover" },
    { expression: "Miss the boat", translation: "Perder una oportunidad" },
    { expression: "No pain, no gain", translation: "Sin dolor no hay ganancia" },
    { expression: "Put all your eggs in one basket", translation: "Poner todos los huevos en una sola cesta" },
    { expression: "Raining cats and dogs", translation: "Lloviendo a cántaros" },
    { expression: "The best of both worlds", translation: "Lo mejor de ambos mundos" },
    { expression: "Under the weather", translation: "Indispuesto" },
    { expression: "You can't judge a book by its cover", translation: "No se puede juzgar un libro por su portada" },
    { expression: "Actions speak louder than words", translation: "Las acciones hablan más fuerte que las palabras" },
    { expression: "All in the same boat", translation: "Todos en el mismo barco" },
    { expression: "Blessing in disguise", translation: "Bendición disfrazada" },
    { expression: "Call it a day", translation: "Dar por terminado el día" },
    { expression: "Don't cry over spilled milk", translation: "No llores por la leche derramada" },
    { expression: "Every cloud has a silver lining", translation: "No hay mal que por bien no venga" },
    { expression: "Get a taste of your own medicine", translation: "Probar tu propia medicina" },
    { expression: "Hit the nail on the head", translation: "Dar en el clavo" },
    { expression: "In the blink of an eye", translation: "En un abrir y cerrar de ojos" },
    { expression: "Keep your fingers crossed", translation: "Cruza los dedos" },
    { expression: "Like two peas in a pod", translation: "Como dos gotas de agua" },
    { expression: "Make a long story short", translation: "Haciendo la historia corta" },
    { expression: "No use crying over spilled milk", translation: "De nada sirve llorar por la leche derramada" },
    { expression: "On the same page", translation: "Estar en la misma página" },
    { expression: "Piece of candy", translation: "Pan comido" },
    { expression: "Put the cart before the horse", translation: "Poner el carro delante de los bueyes" },
    { expression: "Raining buckets", translation: "Lloviendo a cántaros" },
    { expression: "The last straw", translation: "La gota que colma el vaso" },
    { expression: "Up in the air", translation: "En el aire" },
    { expression: "You can't have your cake and eat it too", translation: "No se puede tener todo en la vida" },
    { expression: "All that glitters is not gold", translation: "No todo lo que brilla es oro" },
    { expression: "Barking up the wrong tree", translation: "Buscar en el lugar equivocado" },
    { expression: "Birds of a feather flock together", translation: "Dios los cría y ellos se juntan" },
    { expression: "By the skin of your teeth", translation: "Por los pelos" },
    { expression: "Cut to the chase", translation: "Ir al grano" },
    { expression: "Don't put all your eggs in one basket", translation: "No pongas todos los huevos en la misma cesta" },
    { expression: "Every dog has its day", translation: "Cada perro tiene su día" },
    { expression: "Go the extra mile", translation: "Ir más allá" },
    { expression: "Hit the jackpot", translation: "Ganar el premio gordo" },
    { expression: "Keep your chin up", translation: "Mantén la cabeza en alto" },
    { expression: "Make hay while the sun shines", translation: "Aprovecha mientras brilla el sol" },
    { expression: "No stone unturned", translation: "No dejar piedra sin remover" },
    { expression: "One man's trash is another man's treasure", translation: "Lo que es basura para uno es tesoro para otro" },
    { expression: "Out of the frying pan and into the fire", translation: "De Guatemala a Guatepeor" },
    { expression: "Playing with fire", translation: "Jugar con fuego" },
    { expression: "Saved by the bell", translation: "Salvado por la campana" },
    { expression: "The early bird catches the worm", translation: "Al que madruga, Dios lo ayuda" },
    { expression: "Two heads are better than one", translation: "Cuatro ojos ven más que dos" },
    { expression: "You can't make an omelette without breaking eggs", translation: "No se puede hacer una tortilla sin romper huevos" },
    { expression: "All bark and no bite", translation: "Mucho ruido y pocas nueces" },
    { expression: "Better safe than sorry", translation: "Más vale prevenir que lamentar" },
    { expression: "Cry over spilled milk", translation: "Lamentarse por lo que ya pasó" },
    { expression: "Don't count your chickens before they hatch", translation: "No cuentes tus pollos antes de que salgan del huevo" },
    { expression: "Every cloud has a silver lining", translation: "No hay mal que por bien no venga" },
    { expression: "Get cold feet", translation: "Echarse atrás por miedo" },
    { expression: "Hit the jackpot", translation: "Ganar el premio gordo" },
    { expression: "In hot water", translation: "En problemas" },
    { expression: "Jump on the bandwagon", translation: "Subirse al carro" },
    { expression: "Make a mountain out of a molehill", translation: "Hacer una montaña de un grano de arena" },
    { expression: "No pain, no gain", translation: "Sin dolor, no hay ganancia" },
    { expression: "Over the moon", translation: "Más feliz que una lombriz" },
    { expression: "Put all your eggs in one basket", translation: "Poner todos los huevos en una sola canasta" },
    { expression: "Rain or shine", translation: "Haga sol o llueva" },
    { expression: "The early bird catches the worm", translation: "A quien madruga, Dios lo ayuda" },
    { expression: "Two peas in a pod", translation: "Como dos gotas de agua" },
    { expression: "You're pulling my leg", translation: "Me estás tomando el pelo" },
    { expression: "All in the same boat", translation: "Todos en la misma situación" },
    { expression: "Better late than never", translation: "Más vale tarde que nunca" },
    { expression: "Curiosity killed the cat", translation: "La curiosidad mató al gato" },
    { expression: "Every dog has its day", translation: "A cada cerdo le llega su San Martín" },
    { expression: "Go with the flow", translation: "Dejar que las cosas fluyan" },
    { expression: "Hold your horses", translation: "Cálmate, espera un momento" },
    { expression: "Keep your fingers crossed", translation: "Cruza los dedos, deséalo" },
    { expression: "Like two peas in a pod", translation: "Como dos gotas de agua" },
    { expression: "Make a long story short", translation: "En resumen" },
    { expression: "No use crying over spilled milk", translation: "No sirve de nada llorar sobre la leche derramada" },
    { expression: "On the same page", translation: "En la misma página" },
    { expression: "Rain cats and dogs", translation: "Llover a cántaros" },
    { expression: "The last straw", translation: "La gota que colma el vaso" },
    { expression: "Up in the air", translation: "En el aire" },
    { expression: "You can't have your cake and eat it too", translation: "No se puede tener todo en la vida" },
    { expression: "All that glitters is not gold", translation: "No todo lo que brilla es oro" },
    { expression: "Barking up the wrong tree", translation: "Buscar en el lugar equivocado" },
    { expression: "Birds of a feather flock together", translation: "Dios los cría y ellos se juntan" },
    { expression: "By the skin of your teeth", translation: "Por los pelos" },
    { expression: "Cut to the chase", translation: "Ir al grano" },
    { expression: "Don't put all your eggs in one basket", translation: "No pongas todos los huevos en una sola canasta" },
    { expression: "Every dog has its day", translation: "A cada cerdo le llega su San Martín" },
    { expression: "Go the extra mile", translation: "Ir más allá" },
    { expression: "Hit the jackpot", translation: "Dar en el blanco" },
    { expression: "Keep your chin up", translation: "Mantén la cabeza en alto" },
    { expression: "Make hay while the sun shines", translation: "Aprovecha mientras brille el sol" },
    { expression: "No stone unturned", translation: "No dejes piedra sin mover" },
    { expression: "One man's trash is another man's treasure", translation: "La basura de uno es el tesoro de otro" },
    { expression: "Out of the frying pan and into the fire", translation: "Saltar de Guatemala a Guatepeor" },
    { expression: "Playing with fire", translation: "Jugar con fuego" },
    { expression: "Saved by the bell", translation: "Salvado por la campana" },
    { expression: "The early bird catches the worm", translation: "A quien madruga, Dios lo ayuda" },
    { expression: "Two heads are better than one", translation: "Cuatro ojos ven más que dos" },
    { expression: "You can't make an omelette without breaking eggs", translation: "No se puede hacer una tortilla sin romper huevos" },
    { expression: "All bark and no bite", translation: "Mucho ruido y pocas nueces" },
    { expression: "Better safe than sorry", translation: "Más vale prevenir que lamentar" },
    { expression: "Cry over spilled milk", translation: "Lamentarse por lo que ya pasó" },
    { expression: "Don't count your chickens before they hatch", translation: "No cuentes tus pollos antes de que salgan del huevo" },
    { expression: "Every cloud has a silver lining", translation: "No hay mal que por bien no venga" },
    { expression: "Get cold feet", translation: "Echarse atrás por miedo" },
    { expression: "Hit the jackpot", translation: "Dar en el blanco" },
    { expression: "A picture is worth a thousand words", translation: "Una imagen vale más que mil palabras" },
    { expression: "In hot water", translation: "En aprietos" },
    { expression: "Jump on the bandwagon", translation: "Subirse al carro" },
    { expression: "Make a mountain out of a molehill", translation: "Hacer una montaña de un grano de arena" },
    { expression: "No pain, no gain", translation: "Sin dolor, no hay ganancia" },
    { expression: "Over the moon", translation: "Feliz como una lombriz" },
    { expression: "Put all your eggs in one basket", translation: "Poner todos los huevos en una sola canasta" },
    { expression: "Rain or shine", translation: "Llueva o haga sol" },
    { expression: "The early bird catches the worm", translation: "Al que madruga, Dios le ayuda" },
    { expression: "Two peas in a pod", translation: "Dos gotas de agua" },
    { expression: "You're pulling my leg", translation: "Me estás tomando el pelo" },
    { expression: "All in the same boat", translation: "Todos en la misma barca" },
    { expression: "Actions speak louder than words", translation: "Las acciones hablan más fuerte que las palabras" },
    { expression: "Beauty is in the eye of the beholder", translation: "La belleza está en el ojo del espectador" },
    { expression: "Don't judge a book by its cover", translation: "No juzgues un libro por su portada" },
    { expression: "Every cloud has a silver lining", translation: "No hay mal que por bien no venga" },
];  